spring:
  application:
    name: notify
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/datalogs

server:
  port: 8088
